### ISSUE TITLE
No module named 'logging'

### ISSUE THREAD

**Issue by kvfasil** [kvfasil/waydroid#1]
root@raspberrypi-rdk-mc:/usr/lib/waydroid# waydroid init -c https://waydroid.bardia.tech/OTA/system -v https://waydroid.bardia.tech/OTA/vendor
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 5, in <module>
    import logging
ModuleNotFoundError: No module named 'logging'

**Comment by kvfasil** [comment]
root@raspberrypi-rdk-mc:/usr/lib/waydroid# python3 -V
Python 3.8.2
root@raspberrypi-rdk-mc:/usr/lib/waydroid#
root@raspberrypi-rdk-mc:/usr/lib/waydroid#
root@raspberrypi-rdk-mc:/usr/lib/waydroid# uname -a
Linux raspberrypi-rdk-mc 5.10.52-v7 #1 SMP Tue Jun 14 12:23:48 UTC 2022 armv7l GNU/Linux
root@raspberrypi-rdk-mc:/usr/lib/waydroid#
